package ids

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5/pgxpool"
)

// BigSerialGenerator generates BigSerial IDs
type BigSerialGenerator struct{}

var _ IDGenerator = (*BigSerialGenerator)(nil)

func NewBigSerialGenerator() BigSerialGenerator {
	return BigSerialGenerator{}
}

func (g BigSerialGenerator) Generate() string {
	// BigSerial is generated by the database
	return ""
}

func (g BigSerialGenerator) Name() string {
	return "BIGSERIAL - BIGINT"
}

func (g BigSerialGenerator) CreateTable(ctx context.Context, pool *pgxpool.Pool) error {
	_, err := pool.Exec(ctx, "CREATE TABLE IF NOT EXISTS bigserial_table (id BIGSERIAL PRIMARY KEY, n BIGINT NOT NULL)")
	return err
}

func (g BigSerialGenerator) DropTable(ctx context.Context, pool *pgxpool.Pool) error {
	_, err := pool.Exec(ctx, "DROP TABLE IF EXISTS bigserial_table")
	return err
}

func (g BigSerialGenerator) InsertRecord(ctx context.Context, pool *pgxpool.Pool) error {
	_, err := pool.Exec(ctx, "INSERT INTO bigserial_table DEFAULT VALUES")
	if err != nil {
		return err
	}
	return nil
}

func (g BigSerialGenerator) BulkWriteRecords(ctx context.Context, pool *pgxpool.Pool, count uint64) error {
	_, err := pool.Exec(ctx, "INSERT INTO bigserial_table (n) SELECT g.n FROM generate_series(1, $1) AS g(n)", count)
	return err
}

func (g BigSerialGenerator) CollectStats(ctx context.Context, pool *pgxpool.Pool) (map[string]any, error) {
	stats := make(map[string]any)

	err := LoadPGStatTuple(ctx, pool)
	if err != nil {
		return nil, err
	}

	var tableStats TableStats

	err = pool.QueryRow(ctx, fmt.Sprintf(fmtStatsQuery, "bigserial_table", "bigserial_table", "bigserial_table")).Scan(
		&tableStats.TotalTableSize,
		&tableStats.DataSize,
		&tableStats.IndexSize,
		&tableStats.InternalPages,
		&tableStats.LeafPages,
		&tableStats.Density,
		&tableStats.Fragmentation,
	)
	if err != nil {
		return nil, err
	}

	stats["total_table_size"] = tableStats.TotalTableSize
	stats["data_size"] = tableStats.DataSize
	stats["index_size"] = tableStats.IndexSize
	stats["index_internal_pages"] = tableStats.InternalPages
	stats["index_leaf_pages"] = tableStats.LeafPages
	stats["index_density"] = tableStats.Density
	stats["index_fragmentation"] = tableStats.Fragmentation

	// Calculate the ratio of internal pages to leaf pages
	stats["index_internal_to_leaf_ratio"] = float64(tableStats.InternalPages) / float64(tableStats.LeafPages)

	return stats, nil
}
